nginx:
  container_name: nginx
  image: nginx
  links:
  - php
  volumes:
  - ./:/www
  - ./docker/nginx/conf.d:/etc/nginx/conf.d
  ports:
  - "1111:80"
  - "2222:880"

php:
  container_name: php
  build: docker/php/build
  volumes:
  - ./:/www:rw
  - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  working_dir: /www/


       


  
